package Carreras;
import java.util.Random;
import javax.swing.JOptionPane;

public class FrameCarrerasAutos extends javax.swing.JFrame {

   
    public FrameCarrerasAutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Dado1 = new javax.swing.JLabel();
        NumDado = new javax.swing.JLabel();
        Intento = new javax.swing.JLabel();
        NumIntento = new javax.swing.JLabel();
        BtnInicio = new javax.swing.JButton();
        Car2 = new javax.swing.JLabel();
        Car3 = new javax.swing.JLabel();
        finish = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Car1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Dado2 = new javax.swing.JLabel();
        NumDado1 = new javax.swing.JLabel();
        Intento1 = new javax.swing.JLabel();
        NumIntento1 = new javax.swing.JLabel();
        BtnInicio1 = new javax.swing.JButton();
        BtnJugador1 = new javax.swing.JButton();
        Car4 = new javax.swing.JLabel();
        Car5 = new javax.swing.JLabel();
        finish1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Car6 = new javax.swing.JLabel();
        BtnGuardar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 255, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText(" Juego de Autos  Carrera");

        Dado1.setBackground(new java.awt.Color(0, 204, 51));
        Dado1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dado1.setForeground(new java.awt.Color(51, 204, 255));
        Dado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dado1.setText("Dado");

        NumDado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumDado.setForeground(new java.awt.Color(51, 204, 255));
        NumDado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumDado.setText("0");

        Intento.setBackground(new java.awt.Color(0, 204, 51));
        Intento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Intento.setForeground(new java.awt.Color(51, 204, 255));
        Intento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Intento.setText("Intento");

        NumIntento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumIntento.setForeground(new java.awt.Color(51, 204, 255));
        NumIntento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumIntento.setText("1");

        BtnInicio.setBackground(new java.awt.Color(255, 255, 255));
        BtnInicio.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnInicio.setForeground(new java.awt.Color(51, 204, 255));
        BtnInicio.setText("Inicio");
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });

        Car2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Auto10.png"))); // NOI18N

        Car3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Auto11.png"))); // NOI18N

        finish.setBackground(new java.awt.Color(255, 204, 51));
        finish.setForeground(new java.awt.Color(255, 204, 204));
        finish.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setOpaque(true);

        Car1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto9.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Intento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Car3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Car1)
                                    .addComponent(Car2))
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NumIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202)
                                        .addComponent(Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(NumDado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)))
                .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 206, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumDado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Intento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Car1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Car2)))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Car3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(BtnInicio)))
                .addContainerGap(904, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 899, 1410);

        jLabel9.setBackground(new java.awt.Color(204, 255, 0));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText(" Juego de Autos  Carrera");

        Dado2.setBackground(new java.awt.Color(0, 204, 51));
        Dado2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dado2.setForeground(new java.awt.Color(51, 204, 255));
        Dado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dado2.setText("Dado");

        NumDado1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumDado1.setForeground(new java.awt.Color(51, 204, 255));
        NumDado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumDado1.setText("0");

        Intento1.setBackground(new java.awt.Color(0, 204, 51));
        Intento1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Intento1.setForeground(new java.awt.Color(51, 204, 255));
        Intento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Intento1.setText("Intento");

        NumIntento1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NumIntento1.setForeground(new java.awt.Color(51, 204, 255));
        NumIntento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumIntento1.setText("1");

        BtnInicio1.setBackground(new java.awt.Color(255, 255, 255));
        BtnInicio1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnInicio1.setForeground(new java.awt.Color(51, 204, 255));
        BtnInicio1.setText("Inicio");
        BtnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicio1ActionPerformed(evt);
            }
        });

        BtnJugador1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnJugador1.setForeground(new java.awt.Color(0, 255, 255));
        BtnJugador1.setText("Jugador");
        BtnJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJugador1ActionPerformed(evt);
            }
        });

        Car4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Auto10.png"))); // NOI18N

        Car5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Auto11.png"))); // NOI18N

        finish1.setBackground(new java.awt.Color(255, 204, 51));
        finish1.setForeground(new java.awt.Color(255, 204, 204));
        finish1.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setOpaque(true);

        Car6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto9.png"))); // NOI18N

        BtnGuardar1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BtnGuardar1.setForeground(new java.awt.Color(0, 255, 255));
        BtnGuardar1.setText("Guardar");
        BtnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardar1ActionPerformed(evt);
            }
        });

        jLabel13.setText("jLabel5");

        jLabel14.setText("jLabel5");

        jLabel15.setText("jLabel5");

        jLabel16.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Intento1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Car4)
                                                    .addComponent(Car6)
                                                    .addComponent(Car5))
                                                .addGap(30, 30, 30)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(NumIntento1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(202, 202, 202)
                                                .addComponent(Dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(13, 13, 13))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finish1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(BtnJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(BtnInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(BtnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Intento1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumIntento1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Car6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Car4)
                                        .addGap(20, 20, 20)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(Car5)))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel13)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel14)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel15)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(finish1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnJugador1)
                            .addComponent(BtnInicio1))
                        .addContainerGap(372, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar1)
                        .addGap(501, 501, 501))))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        // TODO add your handling code here:
        
        // Creamos la Función Random para los Números aleatorio
        Random aleatorios = new Random(System.currentTimeMillis());
         // Creamos los intentos de cada carro
         int IntentoAleatorio = aleatorios.nextInt(6*100);
         NumDado.setText(Integer.toString(IntentoAleatorio));
         switch(NumIntento.getText()){
             case "1":{
                Car1.setLocation(Car1.getX()+(10 * IntentoAleatorio), Car1.getY()); 
                if(Car1.getX()> 150){
                    JOptionPane.showInternalMessageDialog(this, "El Car1 Gano la Carrera", "Mensaje", 
                            JOptionPane.WARNING_MESSAGE);
                }else if(Car1.getX()> 250){
                    JOptionPane.showInternalMessageDialog(this, "El Car1 perdio quedo se Segundo",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                } else if(Car1.getX()> 350){
                    JOptionPane.showInternalMessageDialog(this, "El Car1 llego de Tercero",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showInternalMessageDialog(this, "Empate en el Juego de Autos",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
               NumIntento.setText("2");
               break; 
             }
             
            case "2":{
                Car2.setLocation(Car2.getX()+(10 * IntentoAleatorio), Car3.getY()); 
                if(Car2.getX()> 150){
                    JOptionPane.showInternalMessageDialog(this, "El Car2 Gano la Carrera", "Mensaje",
                            JOptionPane.WARNING_MESSAGE);
                }else if(Car2.getX()> 250){
                    JOptionPane.showInternalMessageDialog(this, "El Car2 perdio quedo de Segundo",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                } else if(Car2.getX()> 350){
                    JOptionPane.showInternalMessageDialog(this, "El Car2 llego de Tercero",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showInternalMessageDialog(this, "Empate en el Juego de Autos",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
                 NumIntento.setText("3");
                 break;  
             }
              case "3":{
                Car3.setLocation(Car3.getX()+(10 * IntentoAleatorio), Car3.getY()); 
                if(Car3.getX()> 150){
                    JOptionPane.showInternalMessageDialog(this, "El Car3 Gano la Carrera", "Mensaje", JOptionPane.WARNING_MESSAGE);
                }else if(Car3.getX()> 250){
                    JOptionPane.showInternalMessageDialog(this, "El Car3 perdio quedo se Segundo",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                } else if(Car3.getX()> 350){
                    JOptionPane.showInternalMessageDialog(this, "El Car3 llego de Tercero",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showInternalMessageDialog(this, "Empate en el Juego de Autos",
                            "Mensaje", JOptionPane.WARNING_MESSAGE);
                }
                 NumIntento.setText("3");
                 break;  
             }
              default:{
                 NumIntento.setText("0");
              }
         }
          
         
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInicio1ActionPerformed

    private void BtnJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnJugador1ActionPerformed

    private void BtnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCarrerasAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCarrerasAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCarrerasAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCarrerasAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCarrerasAutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar1;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnInicio1;
    private javax.swing.JButton BtnJugador1;
    private javax.swing.JLabel Car1;
    private javax.swing.JLabel Car2;
    private javax.swing.JLabel Car3;
    private javax.swing.JLabel Car4;
    private javax.swing.JLabel Car5;
    private javax.swing.JLabel Car6;
    private javax.swing.JLabel Dado1;
    private javax.swing.JLabel Dado2;
    private javax.swing.JLabel Intento;
    private javax.swing.JLabel Intento1;
    private javax.swing.JLabel NumDado;
    private javax.swing.JLabel NumDado1;
    private javax.swing.JLabel NumIntento;
    private javax.swing.JLabel NumIntento1;
    private javax.swing.JLabel finish;
    private javax.swing.JLabel finish1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
